return {
  { "ribru17/bamboo.nvim", lazy = true },
  { "bjarneo/aether.nvim", lazy = true },
  { "bjarneo/ethereal.nvim", lazy = true },
  { "bjarneo/hackerman.nvim", lazy = true },
  { "bjarneo/vantablack.nvim", lazy = true },
  { "bjarneo/white.nvim", lazy = true },
  { "catppuccin/nvim", name = "catppuccin", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "kepano/flexoki-neovim", name = "flexoki", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "rebelot/kanagawa.nvim", lazy = true },
  { "tahayvr/matteblack.nvim", lazy = true },
  { "loctvl842/monokai-pro.nvim", lazy = true },
  { "shaunsingh/nord.nvim", lazy = true },
  { "rose-pine/neovim", name = "rose-pine", lazy = true },
  { "folke/tokyonight.nvim", lazy = true },
  { "xero/miasma.nvim", lazy = true },
}
